name: Release a new version on tag

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:

  push-docker:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set IMAGE_REPOSITORY
        run: |
          echo "IMAGE_REPOSITORY=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare tags
        run: |
          v_version=${{ github.ref_name }}
          no_v_version="${v_version#v}"
          echo "v_version=${v_version}" >>${GITHUB_ENV}
          echo "no_v_version=${no_v_version}" >>${GITHUB_ENV}
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/${{ env.IMAGE_REPOSITORY }}:${{ env.v_version }},ghcr.io/${{ env.IMAGE_REPOSITORY }}:${{ env.no_v_version }},ghcr.io/${{ env.IMAGE_REPOSITORY }}:latest
